export const bangladesh = [
  {
    division: "Dhaka",
    districts: [
      "Dhaka",
      "Gazipur",
      "Kishoreganj",
      "Manikganj",
      "Munshiganj",
      "Narayanganj",
      "Narsingdi",
      "Faridpur",
      "Gopalganj",
      "Madaripur",
      "Rajbari",
      "Shariatpur",
      "Tangail",
    ],
  },
  {
    division: "Chattogram",
    districts: [
      "Chattogram",
      "Cox's Bazar",
      "Bandarban",
      "Khagrachari",
      "Rangamati",
      "Feni",
      "Noakhali",
      "Laxmipur",
      "Cumilla",
      "Brahmanbaria",
      "Chandpur",
    ],
  },
  {
    division: "Rajshahi",
    districts: [
      "Rajshahi",
      "Bogra",
      "Joypurhat",
      "Naogaon",
      "Natore",
      "Chapainawabganj",
      "Pabna",
      "Sirajganj",
    ],
  },
  {
    division: "Khulna",
    districts: [
      "Khulna",
      "Bagerhat",
      "Satkhira",
      "Jessore",
      "Jhenaidah",
      "Magura",
      "Narail",
      "Chuadanga",
      "Kushtia",
      "Meherpur",
    ],
  },
  {
    division: "Barishal",
    districts: [
      "Barishal",
      "Patuakhali",
      "Bhola",
      "Pirojpur",
      "Barguna",
      "Jhalokati",
    ],
  },
  {
    division: "Sylhet",
    districts: ["Sylhet", "Sunamganj", "Habiganj", "Moulvibazar"],
  },
  {
    division: "Rangpur",
    districts: [
      "Rangpur",
      "Dinajpur",
      "Thakurgaon",
      "Panchagarh",
      "Nilphamari",
      "Gaibandha",
      "Kurigram",
      "Lalmonirhat",
    ],
  },
  {
    division: "Mymensingh",
    districts: ["Mymensingh", "Jamalpur", "Netrokona", "Sherpur"],
  },
];

export const divisions = [
  {
    name: "Dhaka",
    districts: [
      { name: "Dhaka", shippingCharge: 80 },
      { name: "Gazipur", shippingCharge: 150 },
      { name: "Manikganj", shippingCharge: 150 },
      { name: "Narayanganj", shippingCharge: 150 },
      { name: "Narsingdi", shippingCharge: 150 },
      { name: "Mymensingh", shippingCharge: 150 },
      { name: "Tangail", shippingCharge: 150 },
      { name: "Kishoreganj", shippingCharge: 150 },
      { name: "Faridpur", shippingCharge: 150 },
      { name: "Madaripur", shippingCharge: 150 },
      { name: "Gopalganj", shippingCharge: 150 },
      { name: "Shariatpur", shippingCharge: 150 },
      { name: "Rajbari", shippingCharge: 150 },
    ],
  },
  {
    name: "Chattogram",
    districts: [
      { name: "Chattogram", shippingCharge: 150 },
      { name: "Cox's Bazar", shippingCharge: 150 },
      { name: "Bandarban", shippingCharge: 150 },
      { name: "Rangamati", shippingCharge: 150 },
      { name: "Khagrachari", shippingCharge: 150 },
      { name: "Feni", shippingCharge: 150 },
      { name: "Noakhali", shippingCharge: 150 },
      { name: "Laxmipur", shippingCharge: 150 },
      { name: "Cumilla", shippingCharge: 150 },
      { name: "Brahmanbaria", shippingCharge: 150 },
      { name: "Chandpur", shippingCharge: 150 },
    ],
  },
  {
    name: "Rajshahi",
    districts: [
      { name: "Rajshahi", shippingCharge: 150 },
      { name: "Natore", shippingCharge: 150 },
      { name: "Chapainawabganj", shippingCharge: 150 },
      { name: "Naogaon", shippingCharge: 150 },
      { name: "Pabna", shippingCharge: 150 },
      { name: "Sirajganj", shippingCharge: 150 },
      { name: "Joypurhat", shippingCharge: 150 },
      { name: "Bogura", shippingCharge: 150 },
    ],
  },
  {
    name: "Khulna",
    districts: [
      { name: "Khulna", shippingCharge: 150 },
      { name: "Jessore", shippingCharge: 150 },
      { name: "Satkhira", shippingCharge: 150 },
      { name: "Bagerhat", shippingCharge: 150 },
      { name: "Narail", shippingCharge: 150 },
      { name: "Magura", shippingCharge: 150 },
      { name: "Jhenaidah", shippingCharge: 150 },
      { name: "Chuadanga", shippingCharge: 150 },
      { name: "Meherpur", shippingCharge: 150 },
    ],
  },
  {
    name: "Barishal",
    districts: [
      { name: "Barishal", shippingCharge: 150 },
      { name: "Pirojpur", shippingCharge: 150 },
      { name: "Jhalokati", shippingCharge: 150 },
      { name: "Bhola", shippingCharge: 150 },
      { name: "Barguna", shippingCharge: 150 },
      { name: "Patuakhali", shippingCharge: 150 },
    ],
  },
  {
    name: "Sylhet",
    districts: [
      { name: "Sylhet", shippingCharge: 150 },
      { name: "Sunamganj", shippingCharge: 150 },
      { name: "Moulvibazar", shippingCharge: 150 },
      { name: "Habiganj", shippingCharge: 150 },
    ],
  },
  {
    name: "Rangpur",
    districts: [
      { name: "Rangpur", shippingCharge: 150 },
      { name: "Dinajpur", shippingCharge: 150 },
      { name: "Gaibandha", shippingCharge: 150 },
      { name: "Kurigram", shippingCharge: 150 },
      { name: "Lalmonirhat", shippingCharge: 150 },
      { name: "Nilphamari", shippingCharge: 150 },
      { name: "Panchagarh", shippingCharge: 150 },
      { name: "Thakurgaon", shippingCharge: 150 },
    ],
  },
  {
    name: "Mymensingh",
    districts: [
      { name: "Mymensingh", shippingCharge: 150 },
      { name: "Netrokona", shippingCharge: 150 },
      { name: "Sherpur", shippingCharge: 150 },
      { name: "Jamalpur", shippingCharge: 150 },
    ],
  },
];

console.log(divisions);
